apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - image: abbiyudha/adminservice:latest
          name: admin-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: admin-app-service
  annotations:
    dev.okteto.com/auto-ingress: "domain"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: admin-app